version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3.8"

  producer:
      build: "./producer"
      ports:
        - 8000:8000
      volumes:
        - ./producer:/producer
      environment:
        - SERVICE_ENVIRONMENT=local
      depends_on:
        - rabbitmq
        - mongo
  mongo:
    image: "mongo:4.0"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5000:8081

  notification:
    build: "./notification"
    ports:
      - "6000:6000"
    volumes:
      - ./notification:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - SERVICE_ENVIRONMENT=local
    depends_on:
      - rabbitmq
      - mongo
