version: "3.9"
services:
  producer:
      build: "./producer"
      ports:
        - 8000:8000
      volumes:
        - ./producer:/producer
      environment:
        - SERVICE_ENVIRONMENT=local
      depends_on:
        - rabbitmq
        - mongo
  mongo:
    image: "mongo:4.0"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5000:8081

  rabbitmq:
    image: "rabbitmq:3.8"
