version: "3.9"
services:
  producer:
      build: "./producer"
      ports:
        - 8000:8000
      volumes:
        - ./producer:/producer
      environment:
        - SERVICE_ENVIRONMENT=local
  mongo:
    image: "mongo:4.0"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5000:8081
